#!/usr/bin/env bash
#
#
VERSION="1.0.1"
sudo cp -f direwolf-utils/*.desktop /usr/local/share/applications/
sudo cp -f direwolf-utils/*.sh /usr/local/bin/
cp -f direwolf-utils/*.html /usr/local/share/nexus
nexus-updater.sh piardop,direwolf,pat
exit 0
